### ISSUE TITLE
Crash when logging in: 504 error

### ISSUE THREAD

**Issue by missytake** [deltachat-bot/public-groups-bot#7]
```
[8/12/2020, 10:03:12 PM] Rendering public-groups page for contactId 14
(node:13320) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getName' of null
    at /home/publicgroups/public-groups-bot/src/web_app.js:28:44
    at Array.forEach (<anonymous>)
    at /home/publicgroups/public-groups-bot/src/web_app.js:25:11
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

@Simon-Laux do you have an idea what might be wrong here? It's probably very easy, but my javascript knowledge === 0

**Comment by Simon-Laux** [comment]
have you read the error?

https://github.com/deltachat-bot/public-groups-bot/blob/master/src/web_app.js#L28

`TypeError: Cannot read property 'getName' of null` looks like the chat id is invalid and there is no check build in that checks if the chat exists.

**Comment by Simon-Laux** [comment]
you could try:
```js
chatIds.forEach(chatId => {
    let chat = deltachat.getChat(chatId)
    if (!chat) {
        console.log("chat not found: id=", chatId);
        return
    }
    let data = {
      chatId: chatId,
      chatName: chat.getName(),
    }
    if (deltachat.isContactInChat(chatId, contactId)) {
      joinedChats.push(data)
    } else {
      unjoinedChats.push(data)
    }
})
```
